version: '3.1'

services:
  node-bot:
    build: ./bot
    restart: always
    image: telegram-forwarder-node-bot
    environment:
      AGENT_PORT: 3000
      AGENT_HOSTNAME: python-agent
      TG_API_KEY: '${TG_API_KEY}'
      TG_BOT_USERNAME: '${TG_BOT_USERNAME}'
      DB_HOST: postgres-db
      NTBA_FIX_319: 1
    depends_on:
      - postgres-db
    command: ["./wait-for.sh", "postgres-db:5432", "--", "node", "bot.js"]

  python-agent:
    build: './agent'
    restart: always
    image: 'telegram-forwarder-python-agent'
    depends_on:
      - postgres-db
      - node-bot
    environment:
      API_PORT: 3000
      TG_API_ID: '${TG_API_ID}'
      TG_HASH_ID: '${TG_HASH_ID}'
      DB_HOST: postgres-db
    ports:
      - '3000:3000'
    volumes:
      - './agent/session:/telegram-python-agent/session'

  postgres-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: telegram
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
