api_hash: 85e27071262efb643b2e5ccbde965cfb
api_id: 18492620
chat_id: -1001239523407
file_formats:
  audio:
  - all
  document:
  - pdf
  - jpeg
  video:
  - gif
ids_to_retry: []
last_read_message_id: 37066
media_types:
- audio
- photo
- document
- video
- animation
